[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
meteora_cpi = "2tixmznywHMmRBQehqhuHpg4x2nAzxyCCNPymc5e1id8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
create-lp = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-pool.ts"
gen = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fixtures/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/meteora-cpi.ts"
